name: blog-server-aot

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: euleros-2.10.1
    steps:
      - run: git clone https://gitcode.com/lewist4cj/blog-server.git .

      - run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 --install-dir "$HOME/.dotnet"
          export PATH="$HOME/.dotnet:$PATH"
          echo "dotnet: $(dotnet --version)"

      - run: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet restore
          dotnet publish Blog.Api/Blog.Api.csproj -c Release -r linux-x64 --self-contained -o ./publish
          ls -lh ./publish/
