// <auto-generated />
using System;
using Blog.Core.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Core.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260131163607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("blog.Models.ArticleDiggModel", b =>
                {
                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique()
                        .HasDatabaseName("idx_name");

                    b.ToTable("article_digg_models");
                });

            modelBuilder.Entity("blog.Models.ArticleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CollectCount")
                        .HasColumnType("bigint")
                        .HasColumnName("collect_count");

                    b.Property<long?>("CommentCount")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_count");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<ulong?>("ContentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("content_id");

                    b.Property<string>("Cover")
                        .HasColumnType("longtext")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext")
                        .HasColumnName("desc");

                    b.Property<int?>("EnableComment")
                        .HasColumnType("int")
                        .HasColumnName("enable_comment");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<long?>("LookCount")
                        .HasColumnType("bigint")
                        .HasColumnName("look_count");

                    b.Property<long?>("Status")
                        .HasColumnType("bigint")
                        .HasColumnName("status");

                    b.Property<string>("TagList")
                        .HasColumnType("longtext")
                        .HasColumnName("tag_list");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("article_models");
                });

            modelBuilder.Entity("blog.Models.BannerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cover")
                        .HasColumnType("longtext")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Href")
                        .HasColumnType("longtext")
                        .HasColumnName("href");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("banner_models");
                });

            modelBuilder.Entity("blog.Models.CategoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Title")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("category_models");
                });

            modelBuilder.Entity("blog.Models.CollectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abstract")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("abstract");

                    b.Property<long?>("ArticleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("article_count");

                    b.Property<string>("Cover")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Title")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("collect_models");
                });

            modelBuilder.Entity("blog.Models.CommentModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<string>("Content")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<long?>("DiggCount")
                        .HasColumnType("bigint")
                        .HasColumnName("digg_count");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long?>("RootParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("root_parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RootParentId");

                    b.HasIndex("UserId");

                    b.ToTable("comment_models");
                });

            modelBuilder.Entity("blog.Models.GlobalNotificationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Href")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("href");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("icon");

                    b.Property<string>("Title")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.ToTable("global_notications");
                });

            modelBuilder.Entity("blog.Models.LogModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Addr")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("addr");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Ip")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ip");

                    b.Property<int?>("IsRead")
                        .HasColumnType("int")
                        .HasColumnName("is_read");

                    b.Property<int?>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("LogType")
                        .HasColumnType("int")
                        .HasColumnName("log_type");

                    b.Property<int?>("LoginStatus")
                        .HasColumnType("int")
                        .HasColumnName("login_status");

                    b.Property<int?>("LoginType")
                        .HasColumnType("int")
                        .HasColumnName("login_type");

                    b.Property<string>("Pwd")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("pwd");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("service_name");

                    b.Property<string>("Title")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("log_models");
                });

            modelBuilder.Entity("blog.Models.UserArticleCollectModel", b =>
                {
                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<long?>("CollectId")
                        .HasColumnType("bigint")
                        .HasColumnName("collect_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ArticleId", "CollectId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CollectId");

                    b.HasIndex("UserId", "ArticleId", "CollectId")
                        .IsUnique()
                        .HasDatabaseName("idx_name");

                    b.ToTable("user_article_collect_models");
                });

            modelBuilder.Entity("blog.Models.UserArticleLookHistoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_article_look_history_models");
                });

            modelBuilder.Entity("blog.Models.UserConfModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("LikeTags")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("like_tags");

                    b.Property<int>("PublishCollections")
                        .HasColumnType("int")
                        .HasColumnName("publish_collections");

                    b.Property<int>("PublishFans")
                        .HasColumnType("int")
                        .HasColumnName("publish_fans");

                    b.Property<int>("PublishFollowings")
                        .HasColumnType("int")
                        .HasColumnName("publish_followings");

                    b.Property<long?>("ThemeStyleId")
                        .HasColumnType("bigint")
                        .HasColumnName("theme_style_id");

                    b.Property<DateTime?>("UpdateUsernameDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_username_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uni_user_conf_models_user_id");

                    b.ToTable("user_conf_models");
                });

            modelBuilder.Entity("blog.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abstract")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("abstract");

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("avatar");

                    b.Property<long?>("CodeAge")
                        .HasColumnType("bigint")
                        .HasColumnName("code_age");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nickname");

                    b.Property<string>("OpenId")
                        .HasMaxLength(126)
                        .HasColumnType("varchar(126)")
                        .HasColumnName("open_id");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<sbyte?>("RegisterSrc")
                        .HasColumnType("tinyint")
                        .HasColumnName("register_src");

                    b.Property<sbyte?>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user_models");
                });

            modelBuilder.Entity("blog.Models.ArticleDiggModel", b =>
                {
                    b.HasOne("blog.Models.ArticleModel", "ArticleModel")
                        .WithMany("ArticleDiggs")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("ArticleDiggs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.ArticleModel", b =>
                {
                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("Articles")
                        .HasForeignKey("UserId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.CategoryModel", b =>
                {
                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.CollectModel", b =>
                {
                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("Collects")
                        .HasForeignKey("UserId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.CommentModel", b =>
                {
                    b.HasOne("blog.Models.ArticleModel", "ArticleModel")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.HasOne("blog.Models.CommentModel", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("blog.Models.CommentModel", "RootParentComment")
                        .WithMany()
                        .HasForeignKey("RootParentId");

                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("ArticleModel");

                    b.Navigation("ParentComment");

                    b.Navigation("RootParentComment");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.LogModel", b =>
                {
                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.UserArticleCollectModel", b =>
                {
                    b.HasOne("blog.Models.ArticleModel", "ArticleModel")
                        .WithMany("UserArticleCollects")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Models.CollectModel", "CollectModel")
                        .WithMany()
                        .HasForeignKey("CollectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("UserArticleCollects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleModel");

                    b.Navigation("CollectModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.UserArticleLookHistoryModel", b =>
                {
                    b.HasOne("blog.Models.ArticleModel", "ArticleModel")
                        .WithMany("UserArticleLookHistories")
                        .HasForeignKey("ArticleId");

                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithMany("UserArticleLookHistories")
                        .HasForeignKey("UserId");

                    b.Navigation("ArticleModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.UserConfModel", b =>
                {
                    b.HasOne("blog.Models.UserModel", "UserModel")
                        .WithOne("UserConfig")
                        .HasForeignKey("blog.Models.UserConfModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("blog.Models.ArticleModel", b =>
                {
                    b.Navigation("ArticleDiggs");

                    b.Navigation("Comments");

                    b.Navigation("UserArticleCollects");

                    b.Navigation("UserArticleLookHistories");
                });

            modelBuilder.Entity("blog.Models.UserModel", b =>
                {
                    b.Navigation("ArticleDiggs");

                    b.Navigation("Articles");

                    b.Navigation("Categories");

                    b.Navigation("Collects");

                    b.Navigation("Comments");

                    b.Navigation("Logs");

                    b.Navigation("UserArticleCollects");

                    b.Navigation("UserArticleLookHistories");

                    b.Navigation("UserConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
